name: Deploy to Cloudflare Pages with Bun

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Build with Vite
        run: bun run build

      - name: Upload to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: n5FqpM5yuli4ecYEQsCBqH5wOdJW1ZGarmqjjSoN
          accountId: 4ea2ca30b4c56e40752ff78d120fae93
          projectName: rijan-portofolio
          directory: ./build
          branch: main
